// Mensajes de error para el compilador


char *mensaje_de_error[] = { "",
/*Error 1 */ "Se esperaba declaración de función o procedimiento o main",
/*Error 2 */ "Variable no declarada",
/*Error 3 */ "Variable ya declarada",
/*Error 4 */ "Se esperaba declaración de función o procedimiento",
/*Error 5 */ "Función o procedimiento ya declarado",
/*Error 6 */ "Función o procedimiento no declarado",
/*Error 7 */ "Se esperaba identificador",
/*Error 8 */ "Se esperaba '{'",
/*Error 9 */ "Se esperaba '}'",
/*Error 10*/ "Se esperaba '='",
/*Error 11*/ "Se esperaba ','",
/*Error 12*/ "Se esperaba '<'",
/*Error 13*/ "Se esperaba '>'",
/*Error 14*/ "Se esperaba '['",
/*Error 15*/ "Se esperaba ']'",
/*Error 16*/ "Se esperaba '('",
/*Error 17*/ "Se esperaba ')'",
/*Error 18*/ "Se esperaba ':'",
/*Error 19*/ "Se esperaba ';'",
/*Error 20*/ "Se esperaba comilla doble de apertura ' "" '",
/*Error 21*/ "Se esperaba comilla doble de cierre ' "" '",
/*Error 22*/ "Se esperaba comilla simple de apertura "" ' """,
/*Error 23*/ "Se esperaba comilla simple de cierre "" ' """,
/*Error 24*/ "Se esperaba valor entero",
/*Error 25*/ "Se esperaba valor caracter",
/*Error 26*/ "Se esperaba valor cadena",
/*Error 27*/ "Se esperaba valor flotante",
/*Error 28*/ "Se esperaba valor booleano",
/*Error 29*/ "Se esperaba valor file",
/*Error 30*/ "Se esperaba expresión entera",
/*Error 31*/ "Se esperaba expresión caracter",
/*Error 32*/ "Se esperaba expresión cadena",
/*Error 33*/ "Se esperaba expresión flotante",
/*Error 34*/ "Se esperaba expresión booleana",
/*Error 35*/ "Se esperaba tipo de retorno de la función",
/*Error 36*/ "Se esperaba parámetro por referencia",
/*Error 37*/ "Se esperaba parametro por valor",
/*Error 38*/ "Se esperaba un tipo",
/*Error 39*/ "Se esperaba la palabra 'case'",
/*Error 40*/ "Se esperaba la palabra 'break'",
/*Error 41*/ "Se esperaba la palabra 'until'",
/*Error 42*/ "Símbolo desconocido",
/*Error 43*/ "Error de asignación de tipos",
/*Error 44*/ "La función esperaba mas parametros",
/*Error 45*/ "Se superó el número de parametros esperados la función",
/*Error 46*/ "Fin del archivo",
/*Error 47*/ "Se esperaba la palabra 'do'",
/*Error 48*/ "Se esperaba un valor entero, flotante, caracter o cadena.",
/*Error 49*/ "Se esperaba una funcion de tipo entero",
/*Error 50*/ "Se esperaba una funcion de tipo flotante",
/*Error 51*/ "Se esperaba una funcion de tipo string",
/*Error 52*/ "Se esperaba una funcion de tipo boolean",
/*Error 53*/ "Se esperaba expresión",
/*Error 54*/ "Se esperaba expresion numerica",
/*Error 55*/ "Error en la sintaxis de parametro del tipo arreglo",
/*Error 56*/ "No se declaro ninguna instruccion",
/*Error 57*/ "Error de sintaxis",
/*Error 58*/ "",
/*Error 59*/ "",
/*Error 60*/ "",
/*Error 61*/ "",
/*Error 62*/ "",
/*Error 63*/ "",
/*Error 64*/ "",
/*Error 65*/ "",
/*Error 66*/ "",
/*Error 67*/ "",
/*Error 68*/ "",
/*Error 69*/ "",
/*Error 70*/ "Identificador demasiado largo",
/*Error 71*/ "El numero es demasiado grande",
/*Error 72*/ "La cadena es demasiado grande",
/*Error 73*/ "Tamaño de arreglo demasiado grande",
/*Error 74*/ "",
/*Error 75*/ "",
/*Error 76*/ "",
/*Error 77*/ "",
/*Error 78*/ "",
/*Error 79*/ "",
/*Error 80*/ "" };



/*Errores sintacticos : 1,2,3,4,5,6,7,8,9,10,13,16,17,18,19,20,22,23,24,32 */

/*Errores semanticos  : 11,12,14,15,35*/

/*Limitaciones especificas del compilador : 30,31,33,34*/




